### ISSUE TITLE
Lier NewsLetter à MailChimp

### ISSUE THREAD

**Issue by digitalsciencefactory** [digitalsciencefactory/nao#20]
http://developer.mailchimp.com/documentation/mailchimp/guides/get-started-with-mailchimp-api-3/

**Comment by digitalsciencefactory** [comment]
- [ ] Faire le lien avec MailChimp
Est-ce bien utile ?

**Comment by digitalsciencefactory** [comment]
![fireshot capture 103 - connect your site i mailchimp_ - https___us16 admin mailchimp com_a](https://user-images.githubusercontent.com/29947239/29557296-e8e4916c-8728-11e7-8ed4-5dcdbe154c67.png)

**Comment by digitalsciencefactory** [comment]
<script id="mcjs">!function(c,h,i,m,p){m=c.createElement(h),p=c.getElementsByTagName(h)[0],m.async=1,m.src=i,p.parentNode.insertBefore(m,p)}(document,"script","https://chimpstatic.com/mcjs-connected/js/users/5145f3a338a36a9ceda4d0d8c/bdc700f017b78e1e6bfb7acb2.js");</script>

**Comment by SygoApps** [comment]
Annulé
Vu le 25/08
